/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkflowStepsRouteImport } from "./routes/workflow-steps";
import { Route as WorkflowStepTypesRouteImport } from "./routes/workflow-step-types";
import { Route as UnauthorizedRouteImport } from "./routes/unauthorized";
import { Route as SubscriptionsRouteImport } from "./routes/subscriptions";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as JobTypesRouteImport } from "./routes/job-types";
import { Route as EventsRouteImport } from "./routes/events";
import { Route as EventTypesRouteImport } from "./routes/event-types";
import { Route as ApplicationsRouteImport } from "./routes/applications";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";

const WorkflowStepsRoute = WorkflowStepsRouteImport.update({
  id: "/workflow-steps",
  path: "/workflow-steps",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkflowStepTypesRoute = WorkflowStepTypesRouteImport.update({
  id: "/workflow-step-types",
  path: "/workflow-step-types",
  getParentRoute: () => rootRouteImport,
} as any);
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any);
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: "/subscriptions",
  path: "/subscriptions",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const JobTypesRoute = JobTypesRouteImport.update({
  id: "/job-types",
  path: "/job-types",
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any);
const EventTypesRoute = EventTypesRouteImport.update({
  id: "/event-types",
  path: "/event-types",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: "/applications",
  path: "/applications",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/event-types": typeof EventTypesRoute;
  "/events": typeof EventsRoute;
  "/job-types": typeof JobTypesRoute;
  "/sign-in": typeof SignInRoute;
  "/subscriptions": typeof SubscriptionsRoute;
  "/unauthorized": typeof UnauthorizedRoute;
  "/workflow-step-types": typeof WorkflowStepTypesRoute;
  "/workflow-steps": typeof WorkflowStepsRoute;
  "/auth/callback": typeof AuthCallbackRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/event-types": typeof EventTypesRoute;
  "/events": typeof EventsRoute;
  "/job-types": typeof JobTypesRoute;
  "/sign-in": typeof SignInRoute;
  "/subscriptions": typeof SubscriptionsRoute;
  "/unauthorized": typeof UnauthorizedRoute;
  "/workflow-step-types": typeof WorkflowStepTypesRoute;
  "/workflow-steps": typeof WorkflowStepsRoute;
  "/auth/callback": typeof AuthCallbackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/event-types": typeof EventTypesRoute;
  "/events": typeof EventsRoute;
  "/job-types": typeof JobTypesRoute;
  "/sign-in": typeof SignInRoute;
  "/subscriptions": typeof SubscriptionsRoute;
  "/unauthorized": typeof UnauthorizedRoute;
  "/workflow-step-types": typeof WorkflowStepTypesRoute;
  "/workflow-steps": typeof WorkflowStepsRoute;
  "/auth/callback": typeof AuthCallbackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/applications"
    | "/event-types"
    | "/events"
    | "/job-types"
    | "/sign-in"
    | "/subscriptions"
    | "/unauthorized"
    | "/workflow-step-types"
    | "/workflow-steps"
    | "/auth/callback";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/applications"
    | "/event-types"
    | "/events"
    | "/job-types"
    | "/sign-in"
    | "/subscriptions"
    | "/unauthorized"
    | "/workflow-step-types"
    | "/workflow-steps"
    | "/auth/callback";
  id:
    | "__root__"
    | "/"
    | "/applications"
    | "/event-types"
    | "/events"
    | "/job-types"
    | "/sign-in"
    | "/subscriptions"
    | "/unauthorized"
    | "/workflow-step-types"
    | "/workflow-steps"
    | "/auth/callback";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApplicationsRoute: typeof ApplicationsRoute;
  EventTypesRoute: typeof EventTypesRoute;
  EventsRoute: typeof EventsRoute;
  JobTypesRoute: typeof JobTypesRoute;
  SignInRoute: typeof SignInRoute;
  SubscriptionsRoute: typeof SubscriptionsRoute;
  UnauthorizedRoute: typeof UnauthorizedRoute;
  WorkflowStepTypesRoute: typeof WorkflowStepTypesRoute;
  WorkflowStepsRoute: typeof WorkflowStepsRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflow-steps": {
      id: "/workflow-steps";
      path: "/workflow-steps";
      fullPath: "/workflow-steps";
      preLoaderRoute: typeof WorkflowStepsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflow-step-types": {
      id: "/workflow-step-types";
      path: "/workflow-step-types";
      fullPath: "/workflow-step-types";
      preLoaderRoute: typeof WorkflowStepTypesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/unauthorized": {
      id: "/unauthorized";
      path: "/unauthorized";
      fullPath: "/unauthorized";
      preLoaderRoute: typeof UnauthorizedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/subscriptions": {
      id: "/subscriptions";
      path: "/subscriptions";
      fullPath: "/subscriptions";
      preLoaderRoute: typeof SubscriptionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/job-types": {
      id: "/job-types";
      path: "/job-types";
      fullPath: "/job-types";
      preLoaderRoute: typeof JobTypesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/event-types": {
      id: "/event-types";
      path: "/event-types";
      fullPath: "/event-types";
      preLoaderRoute: typeof EventTypesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applications": {
      id: "/applications";
      path: "/applications";
      fullPath: "/applications";
      preLoaderRoute: typeof ApplicationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  EventTypesRoute: EventTypesRoute,
  EventsRoute: EventsRoute,
  JobTypesRoute: JobTypesRoute,
  SignInRoute: SignInRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WorkflowStepTypesRoute: WorkflowStepTypesRoute,
  WorkflowStepsRoute: WorkflowStepsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
